name: audiobekas
favicon: null
layout_spectrum: 0.4999301719944924
typography_spectrum: 0.19949611742049456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.48243914684280753
  lightness: 0.6293690116144717
  saturation: 0.5031294503714889
  rhythmicContrast: 0.8343772357329726
purpose: []
